[functions.generate-avatar]
enabled = true
verify_jwt = true
import_map = "./functions/generate-avatar/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-avatar/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-avatar/*.html" ]

[functions.public-avatars]
enabled = true
verify_jwt = false
entrypoint = "./functions/public-avatars/index.ts"

[functions.generate-invite-code]
enabled = true
verify_jwt = true
import_map = "./functions/generate-invite-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-invite-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-invite-code/*.html" ]

[functions.redeem-invite]
enabled = true
verify_jwt = true
import_map = "./functions/redeem-invite/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/redeem-invite/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/redeem-invite/*.html" ]
